global:
  namespace: "kube-system"

  # Уникальный идентификатор кластера, будет использоваться при запуске плагина
  clusterID: "5"

  configYaml:
    apiUrl: "__CLOUD_API_URL__"
    projectID: "__PROJECT_ID__"
    regionID: "__REGION_ID__"
    apiToken: "__API_TOKEN__"

images:
  # Контейнеры для Controller
  attacher:
    repository: "harbor.mkaas.edgecenter.online/docker/sig-storage/csi-attacher"
    tag: "v4.7.0"
    pullPolicy: "IfNotPresent"

  provisioner:
    repository: "harbor.mkaas.edgecenter.online/docker/sig-storage/csi-provisioner"
    tag: "v5.1.0"
    pullPolicy: "IfNotPresent"

  snapshotter:
    repository: "harbor.mkaas.edgecenter.online/docker/sig-storage/csi-snapshotter"
    tag: "v8.1.0"
    pullPolicy: "IfNotPresent"

  snapshotController:
    repository: "harbor.mkaas.edgecenter.online/docker/sig-storage/snapshot-controller"
    tag: "v8.2.0"
    pullPolicy: "IfNotPresent"

  resizer:
    repository: "harbor.mkaas.edgecenter.online/docker/sig-storage/csi-resizer"
    tag: "v1.12.0"
    pullPolicy: "IfNotPresent"

  # Контейнеры для Node
  nodeRegistrar:
    repository: "harbor.mkaas.edgecenter.online/docker/sig-storage/csi-node-driver-registrar"
    tag: "v2.8.0"
    pullPolicy: "IfNotPresent"

  # Общий image для EC CSI плагина (и в Controller, и в Node)
  nodeLivenessProbe:
    repository: "harbor.mkaas.edgecenter.online/docker/sig-storage/livenessprobe"
    tag: "v2.14.0"
    pullPolicy: "IfNotPresent"

  ecCsiPlugin:
    repository: "ghcr.io/edge-center/edgecenter-csi"
    tag: "latest"
    pullPolicy: "IfNotPresent"

# Параметры StorageClass
storageClasses:
  standard:
    name: "ec-csi-standard"
    type: "standard"
    setAsDefault: "true"
    allowVolumeExpansion: "true"
    snapshotRestoreEnabled: "true"

  ssdHiiops:
    name: "ec-csi-hiiops"
    type: "ssd_hiiops"
    allowVolumeExpansion: "true"
    snapshotRestoreEnabled: "true"

# Параметры VolumeSnapshotClass
snapshotClass:
  name: "ec-csi-snapshot-class"
  deletionPolicy: "Retain"

# Параметры GroupVolumeSnapshotClass
groupSnapshotClass:
  name: "ec-csi-groupsnapclass"
  deletionPolicy: "Retain"