{{- $standard := .Values.storageClasses.standard -}}
{{- if $standard.name }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $standard.name }}
  {{- if $standard.setAsDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: csi.edgecenter.org
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: {{ $standard.allowVolumeExpansion }}
parameters:
  type: {{ $standard.type }}
  snapshotRestoreEnabled: {{ $standard.snapshotRestoreEnabled | quote  }}
{{- end }}

{{- $ssd := .Values.storageClasses.ssdHiiops -}}
{{- if $ssd.name }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $ssd.name }}
provisioner: csi.edgecenter.org
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: {{ $ssd.allowVolumeExpansion }}
parameters:
  type: {{ $ssd.type }}
  snapshotRestoreEnabled: {{ $ssd.snapshotRestoreEnabled | quote  }}
{{- end }}
