---
apiVersion: v1
kind: Secret
metadata:
  name: ec-csi-plugin-config
  namespace: {{ .Values.global.namespace | quote }}
type: Opaque
data:
  config.yaml: {{ .Values.global.configYaml | toYaml | b64enc }}